CREATE TABLE IF NOT EXISTS offline_packets(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_node TEXT NOT NULL,
    packet_json TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sync_events(
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_login TEXT NOT NULL,
    operation_id TEXT NOT NULL,
    packet_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(account_login, operation_id, packet_type)
);

CREATE TABLE IF NOT EXISTS sync_event_state(
    account_login TEXT PRIMARY KEY,
    retained_floor BIGINT NOT NULL DEFAULT 0,
    latest_cursor BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sync_cursors(
    account_login TEXT NOT NULL,
    node_id TEXT NOT NULL,
    cursor BIGINT NOT NULL DEFAULT 0,
    acknowledged_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(account_login, node_id)
);

CREATE TABLE IF NOT EXISTS processed_mutations(
    account_login TEXT NOT NULL,
    outbox_id TEXT NOT NULL,
    operation_id TEXT NOT NULL DEFAULT '',
    packet_type TEXT NOT NULL DEFAULT '',
    packet_id TEXT NOT NULL DEFAULT '',
    processed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(account_login, outbox_id)
);

CREATE TABLE IF NOT EXISTS account_devices(
    login TEXT NOT NULL REFERENCES accounts(login) ON DELETE CASCADE,
    node_id TEXT NOT NULL,
    display_name TEXT,
    device_name TEXT,
    custom_name TEXT,
    app_version TEXT,
    online INTEGER NOT NULL DEFAULT 0,
    revoked INTEGER NOT NULL DEFAULT 0,
    last_seen TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(login, node_id)
);

CREATE TABLE IF NOT EXISTS email_auth_challenges(
    challenge_id TEXT PRIMARY KEY,
    login TEXT NOT NULL,
    node_id TEXT NOT NULL,
    email TEXT NOT NULL,
    purpose TEXT NOT NULL,
    code_salt TEXT NOT NULL,
    code_hash TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS account_email_trusted_devices(
    login TEXT NOT NULL REFERENCES accounts(login) ON DELETE CASCADE,
    node_id TEXT NOT NULL,
    verified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(login, node_id)
);

CREATE TABLE IF NOT EXISTS account_subscriptions(
    login TEXT NOT NULL REFERENCES accounts(login) ON DELETE CASCADE,
    product TEXT NOT NULL,
    plan_code TEXT NOT NULL DEFAULT 'none',
    status TEXT NOT NULL DEFAULT 'inactive',
    current_period_start TIMESTAMPTZ,
    current_period_end TIMESTAMPTZ,
    cancel_at_period_end INTEGER NOT NULL DEFAULT 0,
    provider TEXT NOT NULL DEFAULT 'manual',
    provider_customer_id TEXT NOT NULL DEFAULT '',
    provider_subscription_id TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(login, product)
);

CREATE TABLE IF NOT EXISTS subscription_events(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login TEXT NOT NULL REFERENCES accounts(login) ON DELETE CASCADE,
    product TEXT NOT NULL,
    event_type TEXT NOT NULL,
    provider_event_id TEXT,
    payload_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS boosty_telegram_links(
    telegram_user_id BIGINT PRIMARY KEY,
    login TEXT NOT NULL UNIQUE REFERENCES accounts(login) ON DELETE CASCADE,
    telegram_username TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'active',
    verified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_checked_at TIMESTAMPTZ,
    access_expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    last_error TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS boosty_activation_codes(
    code_hash TEXT PRIMARY KEY,
    telegram_user_id BIGINT NOT NULL,
    telegram_username TEXT NOT NULL DEFAULT '',
    duration_days INTEGER NOT NULL DEFAULT 30,
    issue_kind TEXT NOT NULL DEFAULT 'legacy',
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    redeemed_login TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS boosty_key_recipients(
    telegram_user_id BIGINT PRIMARY KEY,
    private_chat_id BIGINT NOT NULL,
    telegram_username TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'pending',
    last_membership_check_at TIMESTAMPTZ,
    last_key_issued_at TIMESTAMPTZ,
    next_key_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_error TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vpn_peers(
    peer_id TEXT PRIMARY KEY,
    login TEXT NOT NULL REFERENCES accounts(login) ON DELETE CASCADE,
    product TEXT NOT NULL DEFAULT 'meshpro',
    device_id TEXT NOT NULL,
    address TEXT NOT NULL,
    public_key TEXT NOT NULL,
    config_path TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'provisioning',
    last_applied_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(login, product, device_id)
);

CREATE TABLE IF NOT EXISTS service_sessions(
    token_hash TEXT PRIMARY KEY,
    login TEXT NOT NULL REFERENCES accounts(login) ON DELETE CASCADE,
    service TEXT NOT NULL,
    device_id TEXT NOT NULL DEFAULT '',
    expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS meshpro_usage(
    login TEXT NOT NULL REFERENCES accounts(login) ON DELETE CASCADE,
    feature_id TEXT NOT NULL,
    period_key TEXT NOT NULL,
    used_count INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(login, feature_id, period_key)
);

CREATE TABLE IF NOT EXISTS ai_voice_transcriptions(
    login TEXT NOT NULL REFERENCES accounts(login) ON DELETE CASCADE,
    message_id TEXT NOT NULL,
    text TEXT NOT NULL,
    language TEXT NOT NULL DEFAULT '',
    duration_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(login, message_id)
);

CREATE TABLE IF NOT EXISTS ai_image_ocr(
    login TEXT NOT NULL REFERENCES accounts(login) ON DELETE CASCADE,
    message_id TEXT NOT NULL,
    text TEXT NOT NULL DEFAULT '',
    language TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(login, message_id)
);

CREATE TABLE IF NOT EXISTS web_push_subscriptions(
    endpoint TEXT PRIMARY KEY,
    login TEXT,
    node_id TEXT NOT NULL,
    subscription_json TEXT NOT NULL,
    user_agent TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS direct_messages(
    message_id TEXT PRIMARY KEY,
    sender_node TEXT,
    sender_login TEXT,
    sender_name TEXT,
    receiver_node TEXT,
    receiver_login TEXT,
    message TEXT,
    reply_to_message_id TEXT,
    reply_to_text TEXT,
    message_effect TEXT DEFAULT 'none',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    chat_kind TEXT DEFAULT 'normal',
    chat_id TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS server_groups(
    group_id TEXT PRIMARY KEY,
    group_name TEXT,
    group_about TEXT DEFAULT '',
    group_avatar_data TEXT DEFAULT '',
    members_json TEXT,
    owner_node TEXT,
    admins_json TEXT DEFAULT '[]',
    is_channel INTEGER DEFAULT 0,
    comments_enabled INTEGER DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS server_group_members(
    group_id TEXT NOT NULL REFERENCES server_groups(group_id) ON DELETE CASCADE,
    node_id TEXT NOT NULL,
    login TEXT,
    PRIMARY KEY(group_id, node_id)
);

CREATE TABLE IF NOT EXISTS server_group_keys(
    group_id TEXT NOT NULL REFERENCES server_groups(group_id) ON DELETE CASCADE,
    key_id TEXT NOT NULL,
    member_node TEXT NOT NULL,
    member_login TEXT,
    key_envelope TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(group_id, key_id, member_node)
);

CREATE TABLE IF NOT EXISTS server_group_messages(
    message_id TEXT PRIMARY KEY,
    group_id TEXT,
    group_name TEXT,
    sender_node TEXT,
    sender_login TEXT,
    sender_name TEXT,
    message TEXT,
    reply_to_message_id TEXT,
    reply_to_text TEXT,
    members_json TEXT,
    group_key_id TEXT,
    message_effect TEXT DEFAULT 'none',
    is_channel_comment INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS server_chat_deletes(
    owner_node TEXT NOT NULL,
    peer_node TEXT NOT NULL,
    owner_login TEXT DEFAULT '',
    peer_login TEXT DEFAULT '',
    chat_kind TEXT DEFAULT 'normal',
    chat_id TEXT DEFAULT '',
    deleted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(owner_node, peer_node, chat_kind, chat_id)
);

CREATE TABLE IF NOT EXISTS server_reactions(
    scope TEXT NOT NULL,
    message_id TEXT NOT NULL,
    reactor_node TEXT NOT NULL,
    reactor_login TEXT,
    reactor_identity TEXT NOT NULL DEFAULT '',
    reaction TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(scope, message_id, reactor_node, reaction)
);

CREATE TABLE IF NOT EXISTS server_files(
    file_id TEXT PRIMARY KEY,
    sender_node TEXT,
    sender_login TEXT,
    sender_name TEXT,
    receiver_node TEXT,
    receiver_login TEXT,
    group_id TEXT,
    group_name TEXT DEFAULT '',
    is_channel INTEGER DEFAULT 0,
    comments_enabled INTEGER DEFAULT 1,
    filename TEXT,
    caption TEXT,
    reply_to_message_id TEXT DEFAULT '',
    reply_to_text TEXT DEFAULT '',
    is_channel_comment INTEGER DEFAULT 0,
    data TEXT,
    group_key_id TEXT,
    message_kind TEXT DEFAULT 'file',
    message_effect TEXT DEFAULT 'none',
    storage_path TEXT DEFAULT '',
    sha256 TEXT DEFAULT '',
    size_bytes BIGINT DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    chat_kind TEXT DEFAULT 'normal',
    chat_id TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS file_transfer_sessions(
    account_login TEXT NOT NULL,
    transfer_id TEXT NOT NULL,
    operation_id TEXT NOT NULL DEFAULT '',
    source_node TEXT NOT NULL,
    destination_node TEXT NOT NULL,
    file_id TEXT NOT NULL,
    total_chunks INTEGER NOT NULL,
    chunk_size INTEGER NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 TEXT NOT NULL,
    metadata_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'receiving',
    storage_path TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(account_login, transfer_id)
);

CREATE TABLE IF NOT EXISTS file_transfer_chunks(
    account_login TEXT NOT NULL,
    transfer_id TEXT NOT NULL,
    chunk_index INTEGER NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 TEXT NOT NULL,
    chunk_path TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(account_login, transfer_id, chunk_index),
    FOREIGN KEY(account_login, transfer_id)
        REFERENCES file_transfer_sessions(account_login, transfer_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS server_pins(
    scope TEXT NOT NULL,
    message_id TEXT NOT NULL,
    pinner_node TEXT,
    pinner_login TEXT,
    text TEXT,
    group_key_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(scope, message_id)
);

CREATE TABLE IF NOT EXISTS server_stories(
    story_id TEXT PRIMARY KEY,
    owner_node TEXT,
    owner_login TEXT,
    story_json TEXT NOT NULL,
    recipients_json TEXT DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS server_story_reactions(
    story_id TEXT NOT NULL,
    reactor_node TEXT NOT NULL,
    reactor_login TEXT,
    reaction TEXT NOT NULL,
    liked INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(story_id, reactor_node, reaction)
);

CREATE TABLE IF NOT EXISTS server_story_views(
    story_id TEXT NOT NULL,
    viewer_node TEXT NOT NULL,
    viewer_login TEXT,
    viewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(story_id, viewer_node)
);

CREATE TABLE IF NOT EXISTS server_sticker_libraries(
    login TEXT PRIMARY KEY REFERENCES accounts(login) ON DELETE CASCADE,
    library_json TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS android_push_tokens(
    token TEXT PRIMARY KEY,
    login TEXT,
    node_id TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS account_chat_preferences(
    login TEXT NOT NULL REFERENCES accounts(login) ON DELETE CASCADE,
    chat_key TEXT NOT NULL,
    theme_id TEXT NOT NULL DEFAULT 'midnight',
    bubble_style TEXT NOT NULL DEFAULT 'classic',
    animated_background INTEGER NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(login, chat_key)
);

CREATE TABLE IF NOT EXISTS account_meshpro_preferences(
    login TEXT PRIMARY KEY REFERENCES accounts(login) ON DELETE CASCADE,
    quick_reactions_json TEXT NOT NULL DEFAULT '[]',
    hd_audio INTEGER NOT NULL DEFAULT 1,
    enhanced_noise_suppression INTEGER NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scheduled_messages(
    schedule_id TEXT PRIMARY KEY,
    owner_login TEXT NOT NULL REFERENCES accounts(login) ON DELETE CASCADE,
    source_node TEXT NOT NULL,
    payloads_json TEXT NOT NULL,
    preview_text TEXT NOT NULL DEFAULT '',
    chat_key TEXT NOT NULL DEFAULT '',
    repeat_interval TEXT NOT NULL DEFAULT 'none',
    next_run_at TIMESTAMPTZ NOT NULL,
    last_run_at TIMESTAMPTZ,
    run_count INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_offline_packets_destination_id
ON offline_packets(destination_node, id);
CREATE INDEX IF NOT EXISTS idx_offline_packets_created_at
ON offline_packets(created_at);
CREATE INDEX IF NOT EXISTS idx_sync_events_account_cursor
ON sync_events(account_login, event_id);
CREATE INDEX IF NOT EXISTS idx_processed_mutations_processed_at
ON processed_mutations(processed_at);
CREATE INDEX IF NOT EXISTS idx_email_auth_challenges_login
ON email_auth_challenges(login, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_subscription_provider_event
ON subscription_events(provider_event_id)
WHERE provider_event_id IS NOT NULL AND provider_event_id != '';
CREATE INDEX IF NOT EXISTS idx_boosty_links_status_check
ON boosty_telegram_links(status, last_checked_at);
CREATE INDEX IF NOT EXISTS idx_boosty_codes_user_expiry
ON boosty_activation_codes(telegram_user_id, expires_at, consumed_at);
CREATE INDEX IF NOT EXISTS idx_boosty_codes_user_kind_created
ON boosty_activation_codes(telegram_user_id, issue_kind, created_at);
CREATE INDEX IF NOT EXISTS idx_boosty_recipients_due
ON boosty_key_recipients(status, next_key_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_vpn_peers_active_address
ON vpn_peers(product, address) WHERE status != 'revoked';
CREATE INDEX IF NOT EXISTS idx_vpn_peers_subscription
ON vpn_peers(login, product, status);
CREATE INDEX IF NOT EXISTS idx_service_sessions_login_service
ON service_sessions(login, service, expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_server_reactions_account_unique
ON server_reactions(scope, message_id, reactor_identity, reaction);
CREATE INDEX IF NOT EXISTS idx_file_transfer_sessions_status
ON file_transfer_sessions(status, updated_at);
CREATE INDEX IF NOT EXISTS idx_android_push_tokens_node
ON android_push_tokens(node_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_messages_due
ON scheduled_messages(status, next_run_at);
