ALTER TABLE accounts
ADD COLUMN IF NOT EXISTS privacy_show_online INTEGER NOT NULL DEFAULT 1;

ALTER TABLE accounts
ADD COLUMN IF NOT EXISTS privacy_show_avatar INTEGER NOT NULL DEFAULT 1;

ALTER TABLE accounts
ADD COLUMN IF NOT EXISTS privacy_show_about INTEGER NOT NULL DEFAULT 1;

ALTER TABLE accounts
ADD COLUMN IF NOT EXISTS direct_message_privacy TEXT NOT NULL DEFAULT 'everyone';
